trigger:
- master

pool:
  vmImage: 'windows-latest'
  
variables:
  buildConfiguration: 'release'
  azureSubscription: 'ServiceConnection-MSDN'
  resourceGroup: 'test-infra-rg'
  storageAccountName: 'storagequeue20200322'
  storageQueueName: 'queue1'
  appServicePlan: 'default-plan'
  webAppName: 'WebJobsApp20200322'

steps:
- task: AzureCLI@2
  displayName: Set up environment
  inputs:
    azureSubscription: $(azureSubscription)
    scriptType: ps
    scriptPath: '$(System.DefaultWorkingDirectory)/.pipeline/ops/setup-environment.ps1'
    arguments: '-resourceGroup $(resourceGroup) -storageAccountName $(storageAccountName) -storageQueueName $(storageQueueName) -appServicePlan $(appServicePlan) -webAppName $(webAppName)'
- task: DotNetCoreCLI@2
  displayName: "Publish artifact to staging directory"
  inputs:
    command: publish
    projects: '**/StorageQueueProcessorV2.csproj'
    publishWebProjects: false
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)\app_data\jobs\continuous'
    zipAfterPublish: false
- publish: $(Build.ArtifactStagingDirectory)
  displayName: "Publish artifact to Azure Pipelines"
  artifact: 'StorageQueueProcessor'
- task: AzureRmWebAppDeployment@4
  displayName: 'Azure Web App Deployment'
  inputs:
    appType: webApp
    azureSubscription: $(azureSubscription)
    webAppName: $(webAppName)
    package: $(Build.ArtifactStagingDirectory)
    enableCustomDeployment: true
    deploymentType: 'webDeploy'
    removeAdditionalFilesFlag: true
    excludeFilesFromAppDataFlag: false